sudo: false

language: python

arch:
  - amd64
  - ppc64le

python:
  - pypy
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10-dev
install:
  - pip install tox-travis codecov

script:
  - tox

matrix:
  fast_finish: true

  include:
    - python: 3.9
      env:
      - TOXENV=flake8
    # Power job  
    - python: 3.9
      arch: ppc64le
      env:
      - TOXENV=flake8
  
  exclude:
    - python: pypy
      arch: ppc64le
      
after_success:
  - coverage combine && codecov
