sudo: false

language: python

python:
  - pypy
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install tox-travis codecov

script:
  - tox

matrix:
  fast_finish: true

  include:
    - python: 3.8
      env:
      - TOXENV=flake8

after_success:
  - coverage combine && codecov
